logging:
  level:
    org:
      springframework: OFF
    app:
      com: INFO
spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt
  security:
    user:
      name: monitor
      password: monitor123            
ibm:
  mq:
    queueManager: QMAP01
    channel: MQ.MONITOR.SVRCONN
    connName: localhost(1501)
    sslCipherSpec: TLS_RSA_WITH_AES_128_CBC_SHA256
    sslCipherSpec1: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    useSSL: true
    user: MQmon01
    password: Passw0rd
    authenticateUsingCSP: true
    local: false
    keepMetricsWhenQueueManagerIsDown: false
#    clearMetrics: 5
    event:
      delayInMilliSeconds: 10000          
      queuemanager:
         queue: SYSTEM.ADMIN.QMGR.EVENT
      channel:
         queue: SYSTEM.ADMIN.CHANNEL.EVENT
      config:
         queue: SYSTEM.ADMIN.CONFIG.EVENT
      cpu:
         queue: CPU_SUMMARY
    json:
      sort: true
      order: ascending
    objects:
      queues:
        include: DEAD.LETTER.QUEUE, SYSTEM.ADMIN.COMMAND.QUEUE, SYSTEM.ADMIN.STATISTICS.QUEUE, SYSTEM.ADMIN.ACCOUNTING.QUEUE, "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*"         
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01test.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01test.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus      
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: mq-events-1.0.0.0
    description: IBM MQ Events
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
    ssl:
      key-store: c:\Users\mickm\OneDrive\Documents\Development\tomcat\tomcat.p12
      key-store-password: Passw0rd
      key-store-type: pkcs12
      key-alias: mqevents
      key-password: Passw0rd
    port: 8181